name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - main

jobs:
  test:
    runs-on: ${{ magicwarehq.os }}
    strategy:
      magicwarehq:
        os:
          - ubuntu-latest
          - windows-latest
        node: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ magicwarehq.node }}
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
